/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CofreRouteImport } from './routes/cofre'
import { Route as LembretesRouteImport } from './routes/lembretes'
import { Route as TarefasRouteImport } from './routes/tarefas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CofreRoute = CofreRouteImport.update({
  id: '/cofre',
  path: '/cofre',
  getParentRoute: () => rootRouteImport,
} as any)
const LembretesRoute = LembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cofre': typeof CofreRoute
  '/lembretes': typeof LembretesRoute
  '/tarefas': typeof TarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cofre': typeof CofreRoute
  '/lembretes': typeof LembretesRoute
  '/tarefas': typeof TarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cofre': typeof CofreRoute
  '/lembretes': typeof LembretesRoute
  '/tarefas': typeof TarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/cofre' | '/lembretes' | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/cofre' | '/lembretes' | '/tarefas'
  id: '__root__' | '/' | '/auth' | '/cofre' | '/lembretes' | '/tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CofreRoute: typeof CofreRoute
  LembretesRoute: typeof LembretesRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofre': {
      id: '/cofre'
      path: '/cofre'
      fullPath: '/cofre'
      preLoaderRoute: typeof CofreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembretes': {
      id: '/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof LembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CofreRoute: CofreRoute,
  LembretesRoute: LembretesRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
